# permissions for end users to edit apprevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/managed-by: kustomize
  name: apprevision-editor-role
rules:
- apiGroups:
  - zeitwork.com
  resources:
  - apprevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zeitwork.com
  resources:
  - apprevisions/status
  verbs:
  - get
