# permissions for end users to view apprevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/managed-by: kustomize
  name: apprevision-viewer-role
rules:
- apiGroups:
  - zeitwork.com
  resources:
  - apprevisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zeitwork.com
  resources:
  - apprevisions/status
  verbs:
  - get
